package expert

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

type BuildResult struct {
	RecipeYAML        string
	DockerComposeYAML string
	PlanDir           string
	RecipeID          string
	FilesWritten      []string
}

func BuildArtifacts(plan *ExpertPlan, candidateIndex int, outputDir string) (*BuildResult, error) {
	if candidateIndex < 0 || candidateIndex >= len(plan.Candidates) {
		return nil, fmt.Errorf("candidate index %d out of range (0-%d)", candidateIndex, len(plan.Candidates)-1)
	}

	candidate := plan.Candidates[candidateIndex]
	planID := planIDFromInput(plan.Input)
	planDir := filepath.Join(outputDir, planID)

	if err := os.MkdirAll(planDir, 0755); err != nil {
		return nil, fmt.Errorf("create plan dir: %w", err)
	}

	recipeYAML := generateRecipeYAML(plan, &candidate)
	recipePath := filepath.Join(planDir, "recipe.yaml")
	if err := os.WriteFile(recipePath, []byte(recipeYAML), 0644); err != nil {
		return nil, fmt.Errorf("write recipe.yaml: %w", err)
	}

	composeYAML := generateDockerComposeYAML(plan, &candidate)
	composePath := filepath.Join(planDir, "docker-compose.yaml")
	if err := os.WriteFile(composePath, []byte(composeYAML), 0644); err != nil {
		return nil, fmt.Errorf("write docker-compose.yaml: %w", err)
	}

	envContent := generateEnvFile(plan, &candidate)
	envPath := filepath.Join(planDir, ".env")
	if err := os.WriteFile(envPath, []byte(envContent), 0644); err != nil {
		return nil, fmt.Errorf("write .env: %w", err)
	}

	preflightPath := filepath.Join(planDir, "preflight.sh")
	if err := writeExecutable(preflightPath, generatePreflightScript(plan, &candidate)); err != nil {
		return nil, fmt.Errorf("write preflight.sh: %w", err)
	}

	healthcheckPath := filepath.Join(planDir, "healthcheck.sh")
	if err := writeExecutable(healthcheckPath, generateHealthcheckScript(&candidate)); err != nil {
		return nil, fmt.Errorf("write healthcheck.sh: %w", err)
	}

	benchmarkPath := filepath.Join(planDir, "benchmark.sh")
	if err := writeExecutable(benchmarkPath, generateBenchmarkScript(plan, &candidate)); err != nil {
		return nil, fmt.Errorf("write benchmark.sh: %w", err)
	}

	metadataPath := filepath.Join(planDir, "benchmark-metadata.json")
	if err := os.WriteFile(metadataPath, []byte(generateBenchmarkMetadata(plan, &candidate)), 0644); err != nil {
		return nil, fmt.Errorf("write benchmark-metadata.json: %w", err)
	}

	candidate.Artifacts = map[string]string{
		"recipe_path":        recipePath,
		"compose_path":       composePath,
		"preflight_path":     preflightPath,
		"healthcheck_path":   healthcheckPath,
		"benchmark_path":     benchmarkPath,
		"benchmark_metadata": metadataPath,
		"plan_dir":           planDir,
	}
	plan.Candidates[candidateIndex] = candidate

	recipesRoot, _ := findRecipesExpertDir()
	templateDir := filepath.Join(recipesRoot, "expert", "templates")
	if err := os.MkdirAll(templateDir, 0755); err == nil {
		templateRecipePath := filepath.Join(templateDir, planID+".recipe.yaml")
		_ = os.WriteFile(templateRecipePath, []byte(recipeYAML), 0644)
	}

	result := &BuildResult{
		RecipeYAML:        recipeYAML,
		DockerComposeYAML: composeYAML,
		PlanDir:           planDir,
		RecipeID:          candidate.RecipeID(),
		FilesWritten: []string{
			recipePath,
			composePath,
			envPath,
			preflightPath,
			healthcheckPath,
			benchmarkPath,
			metadataPath,
		},
	}

	return result, nil
}

func writeExecutable(path, content string) error {
	if err := os.WriteFile(path, []byte(content), 0755); err != nil {
		return err
	}
	return nil
}

func planIDFromInput(input ExpertInput) string {
	model := sanitizeForID(input.Model)
	if model == "" {
		model = "custom"
	}
	timestamp := time.Now().Format("20060102-150405")
	return fmt.Sprintf("expert-%s-%s", model, timestamp)
}

func sanitizeForID(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	s = strings.ReplaceAll(s, "/", "-")
	s = strings.ReplaceAll(s, " ", "-")
	s = strings.ReplaceAll(s, "_", "-")
	result := strings.Builder{}
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			result.WriteRune(r)
		}
	}
	return strings.Trim(result.String(), "-")
}

func generateRecipeYAML(plan *ExpertPlan, candidate *CandidateRecipe) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("# Generated by LocalAIStack Expert Alpha\n# Plan: %s\n# Engine: %s, Confidence: %s\n",
		time.Now().Format("2006-01-02 15:04:05"), candidate.Engine, candidate.Confidence))

	if candidate.Reason != "" {
		b.WriteString(fmt.Sprintf("# Reason: %s\n", candidate.Reason))
	}
	for _, risk := range candidate.Risks {
		b.WriteString(fmt.Sprintf("# Risk: %s\n", risk))
	}
	b.WriteString("\n")

	recipeID := candidate.RecipeID()
	b.WriteString(fmt.Sprintf("id: %s\n", recipeID))
	b.WriteString(fmt.Sprintf("name: %s\n", recipeID))
	desc := fmt.Sprintf("Expert-generated %s recipe for %s", candidate.Engine, plan.Input.Model)
	b.WriteString(fmt.Sprintf("description: %s\n", desc))
	b.WriteString("kind: inference\n")
	b.WriteString("tier: expert\n")
	b.WriteString("status: experimental\n")
	b.WriteString(fmt.Sprintf("tags:\n  - %s\n  - expert-generated\n", candidate.Engine))

	b.WriteString("\ntarget:\n")
	b.WriteString("  hardware:\n")
	if plan.Input.Hardware.Vendor != "" {
		b.WriteString(fmt.Sprintf("    vendor: %s\n", plan.Input.Hardware.Vendor))
	}
	if plan.Input.Hardware.VRAMGB > 0 {
		b.WriteString(fmt.Sprintf("    min_vram_gb: %d\n", plan.Input.Hardware.VRAMGB))
	}
	if plan.Input.Constraints.Docker {
		b.WriteString("  os:\n    - linux\n")
		b.WriteString("  runtime:\n    docker: true\n")
		if strings.EqualFold(plan.Input.Hardware.Vendor, "nvidia") {
			b.WriteString("    cuda: \"12.x\"\n")
		}
	}

	b.WriteString("\nmodel:\n")
	b.WriteString(fmt.Sprintf("  source: huggingface\n"))
	b.WriteString(fmt.Sprintf("  id: %s\n", plan.Input.Model))

	if mf, ok := plan.ModelFacts["family"]; ok {
		b.WriteString(fmt.Sprintf("  family: %v\n", mf))
	}
	if mf, ok := plan.ModelFacts["parameter_count"]; ok {
		b.WriteString(fmt.Sprintf("  params: %v\n", mf))
	}
	if mf, ok := plan.ModelFacts["format"]; ok {
		b.WriteString(fmt.Sprintf("  format: %v\n", mf))
	}
	if mf, ok := plan.ModelFacts["quantization"]; ok && mf != "" {
		b.WriteString(fmt.Sprintf("  quantization: %v\n", mf))
	}

	image := engineImageForHardware(candidate.Engine, plan.Input.Hardware.Vendor)
	port := enginePort(candidate.Engine)
	b.WriteString("\nruntime:\n")
	b.WriteString(fmt.Sprintf("  image: %s\n", image))
	b.WriteString("  api: openai-compatible\n")
	b.WriteString(fmt.Sprintf("  port: %d\n", port))
	b.WriteString("  mode: docker-compose\n")

	b.WriteString("\nengine_config:\n")
	for k, v := range candidate.Recipe {
		b.WriteString(fmt.Sprintf("  %s: %v\n", k, v))
	}

	b.WriteString("\nvalidation:\n")
	b.WriteString("  preflight: ./preflight.sh\n")
	b.WriteString("  healthcheck: ./healthcheck.sh\n")
	b.WriteString("  benchmark: ./benchmark.sh\n")

	b.WriteString("\nfallbacks:\n")
	b.WriteString("  oom:\n")
	for _, f := range candidate.Fallbacks {
		b.WriteString(fmt.Sprintf("    - %s\n", f))
	}

	return b.String()
}

func generateDockerComposeYAML(plan *ExpertPlan, candidate *CandidateRecipe) string {
	engine := candidate.Engine
	vendor := plan.Input.Hardware.Vendor
	image := engineImageForHardware(engine, vendor)
	port := enginePort(engine)
	serviceName := fmt.Sprintf("las-expert-%s", engine)

	modelID := plan.Input.Model
	if modelID == "" {
		modelID = "${MODEL_ID}"
	}

	args := engineComposeArgs(engine, modelID, candidate.Recipe)

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# Generated by LocalAIStack Expert Alpha\n# Engine: %s\n\n", engine))
	b.WriteString("services:\n")
	b.WriteString(fmt.Sprintf("  %s:\n", serviceName))
	b.WriteString(fmt.Sprintf("    image: %s\n", image))
	if engine == "vllm" {
		b.WriteString("    network_mode: host\n")
	} else {
		b.WriteString(fmt.Sprintf("    ports:\n      - \"%d:%d\"\n", port, port))
	}
	b.WriteString("    volumes:\n")
	b.WriteString("      - ${HOME}/.cache/huggingface:/root/.cache/huggingface\n")
	if engine == "vllm" {
		b.WriteString("    ipc: host\n")
		b.WriteString("    environment:\n")
		b.WriteString("      VLLM_ENABLE_CUDA_COMPATIBILITY: ${VLLM_ENABLE_CUDA_COMPATIBILITY:-1}\n")
		b.WriteString("      NVIDIA_DISABLE_REQUIRE: ${NVIDIA_DISABLE_REQUIRE:-true}\n")
		b.WriteString("      HF_ENDPOINT: ${HF_ENDPOINT:-}\n")
		b.WriteString("      HTTP_PROXY: ${HTTP_PROXY:-}\n")
		b.WriteString("      HTTPS_PROXY: ${HTTPS_PROXY:-}\n")
		b.WriteString("      ALL_PROXY: ${ALL_PROXY:-}\n")
		b.WriteString("      NO_PROXY: ${NO_PROXY:-localhost,127.0.0.1}\n")
		b.WriteString("      HF_HUB_ETAG_TIMEOUT: ${HF_HUB_ETAG_TIMEOUT:-60}\n")
		b.WriteString("      HF_HUB_DOWNLOAD_TIMEOUT: ${HF_HUB_DOWNLOAD_TIMEOUT:-600}\n")
	}
	if plan.Input.Constraints.Docker && strings.EqualFold(vendor, "nvidia") {
		b.WriteString("    deploy:\n")
		b.WriteString("      resources:\n")
		b.WriteString("        reservations:\n")
		b.WriteString("          devices:\n")
		b.WriteString("            - driver: nvidia\n")
		b.WriteString("              count: 1\n")
		b.WriteString("              capabilities: [gpu]\n")
	}
	b.WriteString("    command: >-\n")
	b.WriteString(fmt.Sprintf("      %s\n", strings.Join(args, " ")))
	return b.String()
}

func engineComposeArgs(engine, modelID string, config map[string]any) []string {
	args := []string{fmt.Sprintf("--model %s", modelID)}

	switch engine {
	case "vllm":
		args = appendEngineArg(args, config, "max_model_len", "--max-model-len")
		args = appendEngineArg(args, config, "gpu_memory_utilization", "--gpu-memory-utilization")
		args = appendBoolFlag(args, config, "enable_prefix_caching", "--enable-prefix-caching")
		args = appendEngineArg(args, config, "tensor_parallel_size", "--tensor-parallel-size")
		args = appendEngineArg(args, config, "quantization", "--quantization")
		args = appendEngineArg(args, config, "dtype", "--dtype")
		args = appendEngineArg(args, config, "max_num_seqs", "--max-num-seqs")
	case "sglang":
		args = appendEngineArg(args, config, "context_length", "--context-length")
		args = appendBoolFlag(args, config, "enable_radix_cache", "--enable-radix-cache")
		args = appendEngineArg(args, config, "mem_fraction_static", "--mem-fraction-static")
		args = appendEngineArg(args, config, "port", "--port")
		args = appendEngineArg(args, config, "host", "--host")
	case "llamacpp":
		args = appendEngineArg(args, config, "ctx_size", "--ctx-size")
		args = appendEngineArg(args, config, "threads", "--threads")
		args = appendEngineArg(args, config, "batch_size", "--batch-size")
		args = appendEngineArg(args, config, "n_gpu_layers", "--n-gpu-layers")
	}

	return args
}

func appendEngineArg(args []string, config map[string]any, key, flag string) []string {
	v, ok := config[key]
	if !ok {
		return args
	}
	return append(args, fmt.Sprintf("%s %v", flag, v))
}

func appendBoolFlag(args []string, config map[string]any, key, flag string) []string {
	v, ok := config[key]
	if !ok {
		return args
	}
	switch val := v.(type) {
	case bool:
		if val {
			return append(args, flag)
		}
	case string:
		if val == "true" {
			return append(args, flag)
		}
	}
	return args
}

func engineImageForHardware(engine, vendor string) string {
	switch engine {
	case "vllm":
		return "${VLLM_IMAGE:-vllm/vllm-openai:v0.6.6}"
	case "sglang":
		return "${SGLANG_IMAGE:-lmsysorg/sglang:latest}"
	case "llamacpp":
		if strings.EqualFold(vendor, "nvidia") {
			return "${LLAMACPP_IMAGE:-ghcr.io/ggml-org/llama.cpp:server-cuda}"
		}
		return "${LLAMACPP_IMAGE:-ghcr.io/ggml-org/llama.cpp:server}"
	default:
		return "${VLLM_IMAGE:-vllm/vllm-openai:v0.6.6}"
	}
}

func generateEnvFile(plan *ExpertPlan, candidate *CandidateRecipe) string {
	var b strings.Builder
	b.WriteString("# LocalAIStack Expert Alpha Environment\n")
	b.WriteString(fmt.Sprintf("# Generated: %s\n", time.Now().Format("2006-01-02 15:04:05")))
	b.WriteString(fmt.Sprintf("\nMODEL_ID=%s\n", plan.Input.Model))
	b.WriteString(fmt.Sprintf("LLM_ENGINE=%s\n", candidate.Engine))
	b.WriteString(fmt.Sprintf("BASE_URL=http://127.0.0.1:%d\n", enginePort(candidate.Engine)))
	b.WriteString("BENCHMARK_STORE=./benchmark-results.jsonl\n")
	switch candidate.Engine {
	case "vllm":
		b.WriteString("VLLM_IMAGE=vllm/vllm-openai:v0.6.6\n")
		b.WriteString("VLLM_ENABLE_CUDA_COMPATIBILITY=1\n")
		b.WriteString("NVIDIA_DISABLE_REQUIRE=true\n")
		b.WriteString("HF_HUB_ETAG_TIMEOUT=60\n")
		b.WriteString("HF_HUB_DOWNLOAD_TIMEOUT=600\n")
	case "sglang":
		b.WriteString("SGLANG_IMAGE=lmsysorg/sglang:latest\n")
	case "llamacpp":
		if strings.EqualFold(plan.Input.Hardware.Vendor, "nvidia") {
			b.WriteString("LLAMACPP_IMAGE=ghcr.io/ggml-org/llama.cpp:server-cuda\n")
		} else {
			b.WriteString("LLAMACPP_IMAGE=ghcr.io/ggml-org/llama.cpp:server\n")
		}
	}
	if plan.Input.Hardware.Vendor != "" {
		b.WriteString(fmt.Sprintf("HARDWARE_VENDOR=%s\n", plan.Input.Hardware.Vendor))
	}
	return b.String()
}

func generatePreflightScript(plan *ExpertPlan, candidate *CandidateRecipe) string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env sh\n")
	b.WriteString("set -eu\n\n")
	b.WriteString("command -v curl >/dev/null 2>&1 || { echo 'curl is required for healthcheck and benchmark' >&2; exit 1; }\n")
	b.WriteString("command -v docker >/dev/null 2>&1 || { echo 'docker is required for this generated compose recipe' >&2; exit 1; }\n")
	if plan.Input.Constraints.Docker && strings.EqualFold(plan.Input.Hardware.Vendor, "nvidia") {
		b.WriteString("docker info 2>/dev/null | grep -qi nvidia || echo 'warning: Docker NVIDIA runtime was not detected; run nvidia-ctk runtime configure --runtime=docker if GPU is unavailable' >&2\n")
	}
	b.WriteString(fmt.Sprintf("echo 'preflight OK for %s (%s)'\n", candidate.RecipeID(), candidate.Engine))
	return b.String()
}

func generateHealthcheckScript(candidate *CandidateRecipe) string {
	return fmt.Sprintf(`#!/usr/bin/env sh
set -eu

BASE_URL="${BASE_URL:-http://127.0.0.1:%d}"
SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/.env" ]; then
  set -a
  . "$SCRIPT_DIR/.env"
  set +a
fi
MODEL_ID="${MODEL_ID:-local-model}"

curl --noproxy '*' -fsS "$BASE_URL/v1/models" >/dev/null

curl --noproxy '*' -fsS "$BASE_URL/v1/chat/completions" \
  -H 'Content-Type: application/json' \
  -d "{\"model\":\"$MODEL_ID\",\"messages\":[{\"role\":\"user\",\"content\":\"Reply with OK.\"}],\"max_tokens\":8,\"temperature\":0}" >/dev/null

echo "healthcheck OK"
`, enginePort(candidate.Engine))
}

func generateBenchmarkScript(plan *ExpertPlan, candidate *CandidateRecipe) string {
	recipeID := candidate.RecipeID()
	engine := candidate.Engine
	modelID := shellEscape(plan.Input.Model)
	runtimeConfig := shellEscape(flattenConfig(candidate.Recipe))
	hardwareSummary := shellEscape(flattenFacts(plan.HardwareFacts))
	modelSummary := shellEscape(flattenFacts(plan.ModelFacts))

	return fmt.Sprintf(`#!/usr/bin/env sh
set -eu

BASE_URL="${BASE_URL:-http://127.0.0.1:%d}"
SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
if [ -f "$SCRIPT_DIR/.env" ]; then
  set -a
  . "$SCRIPT_DIR/.env"
  set +a
fi
MODEL_ID="${MODEL_ID:-%s}"
BENCHMARK_STORE="${BENCHMARK_STORE:-./benchmark-results.jsonl}"
PROMPT="${PROMPT:-Say OK in one short sentence.}"

START_MS=$(date +%%s000)
curl --noproxy '*' -fsS "$BASE_URL/v1/chat/completions" \
  -H 'Content-Type: application/json' \
  -d "{\"model\":\"$MODEL_ID\",\"messages\":[{\"role\":\"user\",\"content\":\"$PROMPT\"}],\"max_tokens\":32,\"temperature\":0}" >/dev/null
END_MS=$(date +%%s000)
LATENCY_MS=$((END_MS - START_MS))

mkdir -p "$(dirname "$BENCHMARK_STORE")"
printf '{"created_at":"%%s","recipe_id":"%s","engine":"%s","model_id":"%%s","latency_ms":%%s,"hardware_facts":"%s","model_facts":"%s","runtime_config":"%s"}\n' \
  "$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)" "$MODEL_ID" "$LATENCY_MS" >> "$BENCHMARK_STORE"

echo "benchmark recorded: $BENCHMARK_STORE"
`, enginePort(candidate.Engine), modelID, recipeID, engine, hardwareSummary, modelSummary, runtimeConfig)
}

func generateBenchmarkMetadata(plan *ExpertPlan, candidate *CandidateRecipe) string {
	return fmt.Sprintf(`{
  "recipe_id": %q,
  "engine": %q,
  "model_id": %q,
  "hardware_facts": %s,
  "model_facts": %s,
  "runtime_config": %s,
  "result_store": "benchmark-results.jsonl"
}
`, candidate.RecipeID(), candidate.Engine, plan.Input.Model, jsonish(plan.HardwareFacts), jsonish(plan.ModelFacts), jsonish(candidate.Recipe))
}

func flattenConfig(config map[string]any) string {
	parts := make([]string, 0, len(config))
	for k, v := range config {
		parts = append(parts, fmt.Sprintf("%s=%v", k, v))
	}
	return strings.Join(parts, ",")
}

func flattenFacts(facts map[string]any) string {
	parts := make([]string, 0, len(facts))
	for k, v := range facts {
		parts = append(parts, fmt.Sprintf("%s=%v", k, v))
	}
	return strings.Join(parts, ",")
}

func jsonish(v any) string {
	if v == nil {
		return "{}"
	}
	data, err := json.Marshal(v)
	if err != nil {
		return "{}"
	}
	return string(data)
}

func shellEscape(s string) string {
	return strings.ReplaceAll(s, `"`, `\"`)
}

func enginePort(engine string) int {
	switch engine {
	case "vllm":
		return 8000
	case "sglang":
		return 30000
	case "llamacpp":
		return 8080
	default:
		return 8000
	}
}

func findRecipesExpertDir() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		candidate := filepath.Join(cwd, "recipes")
		if info, err := os.Stat(candidate); err == nil && info.IsDir() {
			return candidate, nil
		}
		parent := filepath.Dir(cwd)
		if parent == cwd {
			break
		}
		cwd = parent
	}
	return "", fmt.Errorf("recipes directory not found")
}

func CandidateRecipeID(c *CandidateRecipe) string {
	if c == nil {
		return ""
	}
	return c.RecipeID()
}

func (c CandidateRecipe) RecipeID() string {
	if c.Engine == "" {
		return "expert-unknown"
	}
	return fmt.Sprintf("expert.%s", c.Engine)
}
